<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<?php

$i=0;
if($_SERVER['REQUEST_METHOD']=='GET'&&isset($_GET["calculate"]))
{
    include 'connection.php';
    function getaddress($lat,$lng)
    {
      $url = 'http://maps.googleapis.com/maps/api/geocode/json?latlng='.trim($lat).','.trim($lng).'&sensor=false';
      $json = @file_get_contents($url);
      $data=json_decode($json);
      $status = $data->status;
     if($status=="OK")
     return $data->results[0]->formatted_address;
      else
      return false;
    } 
    function converter($num)
    {
    $num4=$num/100;
    $intpart= floor($num4);
    //echo " Degree part is :$intpart";
    $num4=$num4*100;
    $intpart1=$intpart*100;
    $minute=$num4-$intpart1;
    $minute1= floor($minute);
    //echo "<br>";
    //echo "Minute part is :$minute1";
    $minute=$minute*100;
    $minute2=$minute1*100;
    $second=$minute-$minute2;
    $second= floor($second);
   // echo "<br>";
   // echo "Second part is:$second";
    $decimal=($intpart + $minute1/60 + $second/3600);
    //echo "<br>";
   // echo "The converted value in decimal:$decimal";
    return $decimal;
    }
    $lat=$_GET["corx1"];
    $lon=$_GET["cory1"];
    $id=$_GET["aksid"];
    $unit="K";
    $lat1=($lat/100);
    $lon1=($lon/100);
    
    $adrs= getaddress($lat1,$lon1);
    function distance($lat1, $lon1, $lat2, $lon2, $unit) {
	 
	  $theta = $lon1 - $lon2;
	  $dist = sin(deg2rad($lat1)) * sin(deg2rad($lat2)) +  cos(deg2rad($lat1)) * cos(deg2rad($lat2)) * cos(deg2rad($theta));
	  $dist = acos($dist);
	  $dist = rad2deg($dist);
	  $miles = $dist * 60 * 1.1515;
	  $unit = strtoupper($unit);
	  if ($unit == "K") {
               return ($miles * 1.609344);
	  } else if ($unit == "N") {
	      return ($miles * 0.8684);
	    } else {
	        return $miles;
	      }
	}
         $query=mysql_query("select * from distance ");
              
	while($row=mysql_fetch_array($query))
        {
            $x_cor[]=$row[1];
            $y_cor[]=$row[2];
            
        }
        for($j=0;$j<count($x_cor);$j++){
	$dist[]=distance($lat1,$lon1,$x_cor[$j],$y_cor[$j],$unit);
	$dist1[]=distance($lat1,$lon1,$x_cor[$j],$y_cor[$j],$unit);
	}
        sort($dist);
        for($j=0;$j<count($dist);$j++){
		if($dist1[$j]==$dist[0])
		{
			$m1=$j;
			}
		if($dist1[$j]==$dist[1])
		{
			$m2=$j;
			}
		if($dist1[$j]==$dist[2])
		{
			$m3=$j;
			}

			}
         $x_lat[]=array($x_cor[$m1],$x_cor[$m2],$x_cor[$m3]);
      $y_lon[]=array($y_cor[$m1],$y_cor[$m2],$y_cor[$m3]);      
    
   
    
    $m1++;$m2++;$m3++;
        echo "<br>";
        $query=mysql_query("select * from distance where ID='$m1' ");
              $row=mysql_fetch_array($query);
              $policeaddress=$row['ADDRESS'];
              $email=$row['EMAIL'];
              $phone=$row['PHONE_NO'];
       $query1=mysql_query("select * from distance where ID='$m2' ");
              $row=mysql_fetch_array($query1);
              $policeaddress2=$row['ADDRESS'];
              $email2=$row['EMAIL'];
              $phone2=$row['PHONE_NO'];
       $query2=mysql_query("select * from distance where ID='$m3' ");
              $row=mysql_fetch_array($query2);
              $policeaddress3=$row['ADDRESS'];
              $email3=$row['EMAIL'];
              $phone3=$row['PHONE_NO'];
        $result3 = mysql_query("SELECT * FROM member_fin where AKS_ID='$id'");
        while($row3 = mysql_fetch_array($result3))
        { 
            $fname=$row3['FNAME'];
            $lname=$row3['LNAME'];
            $address=$row3['ADDRESS'];
            $contact=$row3['CONTACT'];
            
            $gender=$row3['GENDER'];
        }
     
        
        
         
}
        
?>
<?php
if($_SERVER['REQUEST_METHOD']=='GET'&&isset($_GET["calculate"]))
{
$emailto=$email;
$emailto1=$email2;
$emailto2=$email3;
$link="http://ads.cgvigyansabha.in/find.php?corx1=".$lat."&cory1=".$lon."&aksid=".$id."&calculate=Calculate";
$emailBody1 = "Respected Sir, this mail has been automatically generated by ADS. A girl named ".$fname." ".$lname." is  ".$dist[0]." Kilometers away from your police station, near ".$adrs." and is in trouble. Please help \nVictim's Profile \nName: ".$fname." ".$lname."\nAddress :".$address."\nContact :".$contact."\nGender: ".$gender."\nLink: ".$link;
$emailBody2 = "Respected Sir, this mail has been automatically generated by ADS. A girl named ".$fname." ".$lname." is  ".$dist[1]." Kilometers away from your police station, near ".$adrs." and is in trouble. Please help \nVictim's Profile \nName: ".$fname." ".$lname."\nAddress :".$address."\nContact :".$contact."\nGender: ".$gender."\nLink: ".$link;
$emailBody3 = "Respected Sir, this mail has been automatically generated by ADS. A girl named ".$fname." ".$lname." is  ".$dist[2]." Kilometers away from your police station, near ".$adrs." and is in trouble. Please help \nVictim's Profile \nName: ".$fname." ".$lname."\nAddress :".$address."\nContact :".$contact."\nGender: ".$gender."\nLink: ".$link;

   

$headers = 'From: aditya@cgvigyansabha.in' . "\r\n" .
    'Reply-To: astroadityachauhan@gmail.com' . "\r\n" .
    'X-Mailer: PHP/' . phpversion();

mail($emailto, 'ADS ALERT', $emailBody1);
mail($emailto1, 'ADS ALERT', $emailBody2);
mail($emailto2, 'ADS ALERT', $emailBody3);
}
?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<link rel="stylesheet" type="text/css" href="style.css" />
<title>Accident Detection System</title>
</head>
<body>

<div id="wrap">

<div id="header">
<h1><a href="#">Accident Detection System</a></h1>
</div>

<div id="menu">
<ul>
<li><a href="index.html">Home</a></li>
<li><a href="about.html">About</a></li>
<li><a href="ads_index.php">Registration</a></li>
<li><a href="#">Discussions</a></li>
<li><a href="#">Downloads</a></li>
<li><a href="tofindaddress.php">Find Location</a></li>
<li><a href="find.php">Find</a></li>
<li><a href="#">Contact</a></li>
</ul>
</div>

<div id="contentwrap"> 

<div id="content">

<h2>Accident Detection System</h2>
<p align="justify">
    <font style="bold">
        <b>

            <table border="1">
                <thead>
                    <tr>
                        <th>S_NO</th>
                        <th>ID</th>
                        <th>NAME</th>
                        <th>CONTACT</th>
                        <th>DISTANCE</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>1</td>
                        <td><?php if($_SERVER['REQUEST_METHOD']=='GET'&&isset($_GET["calculate"])){ echo $m1; }?></td>
                        <td><?php if($_SERVER['REQUEST_METHOD']=='GET'&&isset($_GET["calculate"])){ echo $policeaddress; }?></td>
                        <td><?php if($_SERVER['REQUEST_METHOD']=='GET'&&isset($_GET["calculate"])){ echo $phone; }?></td>
                        <td><?php if($_SERVER['REQUEST_METHOD']=='GET'&&isset($_GET["calculate"])){ echo $dist[0]; }?></td>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td><?php if($_SERVER['REQUEST_METHOD']=='GET'&&isset($_GET["calculate"])){ echo $m2; }?></td>
                        <td><?php  if($_SERVER['REQUEST_METHOD']=='GET'&&isset($_GET["calculate"])){ echo $policeaddress2; }?></td>
                        <td><?php if($_SERVER['REQUEST_METHOD']=='GET'&&isset($_GET["calculate"])){ echo $phone2; }?></td>
                        <td><?php if($_SERVER['REQUEST_METHOD']=='GET'&&isset($_GET["calculate"])){ echo $dist[1]; }?></td>
                    </tr>
                    <tr>
                        <td>3</td>
                        <td><?php if($_SERVER['REQUEST_METHOD']=='GET'&&isset($_GET["calculate"])){ echo $m3; }?></td>
                        <td><?php if($_SERVER['REQUEST_METHOD']=='GET'&&isset($_GET["calculate"])){ echo $policeaddress3; }?></td>
                        <td><?php if($_SERVER['REQUEST_METHOD']=='GET'&&isset($_GET["calculate"])){ echo $phone3; }?></td>
                        <td><?php if($_SERVER['REQUEST_METHOD']=='GET'&&isset($_GET["calculate"])){ echo $dist[2]; }?></td>
                    </tr>
                    
                </tbody>
            </table>

            

</b></font></p>
<div id="map" style="width:450px;height:350px; margin-top:10px;"></div>
<p>     
<?php
        if($_SERVER['REQUEST_METHOD']=='GET'&&isset($_GET['calculate']))
        {
            //echo "<img src='uploads/DSC_0510.JPG />";
            echo "Victims Profile: <br>";
?>
<img style="float: left; padding: 0 10px 10px 0;" src="uploads/<?php echo $id ?>.jpg" width="175" height="200" alt="astro image example"/>
            <?php 
           
           
            echo "First Name: ".$fname."<br><br>";
            echo "Last Name: ".$lname."<br><br>";
            echo "Gender: ".$gender."<br><br>";
            echo "Contact: ".$contact."<br><br>";
            echo "Address: ".$address."<br><br>";

           
           $msg="Dear Sir,We are speaking from ADS, a ".$gender." named ".$fname." ".$lname." is in trouble. Please help !! ";
echo "<br>";
        }
   ?>

</p>
    

<p>
<img style="float: left; padding: 0 10px 10px 0;" src="akshara.gif" width="190" height="200" alt="astro image example" />
<form action="<?php htmlspecialchars($_SERVER["PHP_SELF"]); ?>" method="GET">
            Enter coordinates of x<br> <input type="text" name="corx1" value="" /><br>
            Enter coordinates of y<br> <input type="text" name="cory1" value="" /><br>
            Enter ADS Number<br>      <input type="text" name="aksid" value="" /><br>
              
            <input type="submit" value="Calculate" name="calculate" />
        </form> 
</p>

</div>

<div id="sidebar">
<h3>What's New</h3>
<marquee behavior="scroll" direction="up" behaviour="slide" onmouseover="this.stop()" onmouseout="this.start()" scrollamount="2" scrolldelay="1">
<ul>
<li><a href="#">Akshara trends in the market</a></li>
<li><a href="#">Akshara awarded best product award</a></li>
<li><a href="#">Akshara saves 9999 lives so far</a></li>
<li><a href="#">Akshara been catalysed by a lot of NGOs</a></li>
<li><a href="#">Akshara seems to be the new fashion</a></li>
<li><a href="#">Developers working on other versions of Akshara</a></li>
<li><a href="#">Akshara </a></li>
</ul>
</marquee>

<h3>Useful Resources</h3>
<ul>
<li><a href="#">Old Wisdom</a></li>
</ul>

</div>

<div style="clear: both;"> </div>

</div>

<div id="footer">
<p>&copy; Copyright 2016 Accident Detection System </div>

</div>
              
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<script src="http://maps.google.com/maps/api/js?sensor=false" type="text/javascript"></script>
<script type="text/javascript">
$(document).ready(function () {
// Define the latitude and longitude positions
var latitude = parseFloat("<?php echo $lat1; ?>"); // Latitude get from above variable
var longitude = parseFloat("<?php echo $lon1; ?>"); // Longitude from same
var latlngPos = new google.maps.LatLng(latitude, longitude);
// Set up options for the Google map
var myOptions = {
zoom: 15,
center: latlngPos,
mapTypeId: google.maps.MapTypeId.ROADMAP,
zoomControlOptions: true,
zoomControlOptions: {
style: google.maps.ZoomControlStyle.LARGE
}
};
// Define the map
map = new google.maps.Map(document.getElementById("map"), myOptions);
// Add the marker
var marker = new google.maps.Marker({
position: latlngPos,
map: map,
title: "test"
});
});
</script>          

</body>
</html>
